### PR TITLE
Now you can ping yourself again

### PR DESCRIPTION
**Pull request by Elnathbeta**
Solves #3

### CODE REVIEW

**Comment by lodart** [comment]
mucho better. 3.74/5.42 
many wow.

**Review by vgaudard — CHANGES_REQUESTED** [review]
Undocumented changes

**Comment by Elnathbeta** [comment]
The code is not commented, so it's coherent with the "coding guidelines"

**Comment by vgaudard** [comment]
Check [this file](https://github.com/vgaudard/discordbots/blob/master/src/plugins/diplodocus.rb#L3). It's wonderfully commented.
Please change this.

**Review by vgaudard — CHANGES_REQUESTED** [review]
Your modifications failed some tests because of a junk string.
Please test your changes before committing.

**Review by vgaudard — APPROVED** [review]

**Comment by lodart** [comment]
Dayum :/

**Pull request merged**
